### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by FxPouya** [CryptoCompareLTD/streaming-guides#6]
Hello,
When I run nodejs streaming example get below error:
{ Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at TLSSocket.socketOnEnd (_http_client.js:426:23)
    at TLSSocket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
disconnected

I put API key(generated free api key).
any solution?
Regards,

**Comment by karbica** [comment]
+1
